spring:
  security:
    oauth2:
      client:
        registration:
          spotify:
            client-secret: ${SPOTIFY_CLIENT_SECRET}
            client-id: ${SPOTIFY_CLIENT_ID}
        provider:
          spotify:
            scopes:
            redirect-uri: "http://localhost:4200/login/success"
            authorization-uri: "https://accounts.spotify.com/authorize"
            token-uri: "https://accounts.spotify.com/api/token"
            authorization-grant-type: "client_credentials"